import { createSlice, nanoid } from "@reduxjs/toolkit";

const initialState = {
  todos: [{ id: 1, text: "Hello world" }],
};

 const todoSlice = createSlice({
  name: "todo",
  initialState,
  reducers: {

    //reducer 1
    addTodo: (state, action) => {
      const todo = {
        id: nanoid(),
        text: action.payload, //jab bhi addtodo() call hoga, tooh jo bhi values as an argument aengee wo 
      };                     //"action.payload" mai store honee hongee.
      state.todos.push(todo);
    },

    //reducer 2
    removeTodo: (state, action) => {
      state.todos = state.todos.filter((todo) => todo.id !== action.payload);
    },
  },
});

export const { addTodo, removeTodo } = todoSlice.actions;

export default todoSlice.reducer; //This is the reducer function generated by createSlice that contains
//  all the reducers. This reducer function will be used in our store to update the state.
